@hostname = http://localhost
@port = 5056
@host = {{hostname}}:{{port}}/api/Folder

### Create Folder
POST {{host}}/folder HTTP/1.1
Content-Type: application/json

{
  "name": "Test",
  "path": "C:\\Users\\Christian\\Desktop\\File\\Picture\\Test",
  "size": 12,
  "userId": 1,
  "isDeleted": true
}

### Called All Files
@path = File/Picture
GET {{host}}/View/{{path}} HTTP/1.1